// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VacApp_Bovinova_Platform.Shared.Infrastructure.Persistence.EFC.Configuration;

#nullable disable

namespace VacApp_Bovinova_Platform.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250705000655_CreateAdminTable")]
    partial class CreateAdminTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("VacApp_Bovinova_Platform.CampaignManagement.Domain.Model.Aggregates.Campaign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("CampaignUserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("end-date");

                    b.Property<int>("GoalId")
                        .HasColumnType("int")
                        .HasColumnName("goal-id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<int?>("StableId")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("stable-id");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("start-date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("p-k_campaigns");

                    b.HasIndex("StableId")
                        .HasDatabaseName("i-x_campaigns_stable-id");

                    b.ToTable("campaigns");
                });

            modelBuilder.Entity("VacApp_Bovinova_Platform.CampaignManagement.Domain.Model.Aggregates.Channel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("CampaignId")
                        .HasColumnType("int")
                        .HasColumnName("campaign-id");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("details");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("p-k_channels");

                    b.HasIndex("CampaignId")
                        .HasDatabaseName("i-x_channels_campaign-id");

                    b.ToTable("channels");
                });

            modelBuilder.Entity("VacApp_Bovinova_Platform.CampaignManagement.Domain.Model.Aggregates.Goal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("CampaignId")
                        .HasColumnType("int")
                        .HasColumnName("campaign-id");

                    b.Property<int>("CurrentValue")
                        .HasColumnType("int")
                        .HasColumnName("current-value");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("Metric")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("metric");

                    b.Property<int>("TargetValue")
                        .HasColumnType("int")
                        .HasColumnName("target-value");

                    b.HasKey("Id")
                        .HasName("p-k_goals");

                    b.HasIndex("CampaignId")
                        .HasDatabaseName("i-x_goals_campaign-id");

                    b.ToTable("goals");
                });

            modelBuilder.Entity("VacApp_Bovinova_Platform.IAM.Domain.Model.Aggregates.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("created-at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("email-confirmed");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("updated-at");

                    b.HasKey("Id")
                        .HasName("p-k_admins");

                    b.ToTable("admins");
                });

            modelBuilder.Entity("VacApp_Bovinova_Platform.IAM.Domain.Model.Aggregates.Credential", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("user-id");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("access-token");

                    b.Property<long?>("ExpiresInSeconds")
                        .HasColumnType("bigint")
                        .HasColumnName("expires-in-seconds");

                    b.Property<string>("IdToken")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("id-token");

                    b.Property<DateTime>("IssuedUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("issued-utc");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("refresh-token");

                    b.HasKey("UserId")
                        .HasName("p-k_credentials");

                    b.ToTable("credentials");
                });

            modelBuilder.Entity("VacApp_Bovinova_Platform.IAM.Domain.Model.Aggregates.MicrosoftCredential", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("user-id");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("access-token");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<DateTime>("IssuedUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("issued-utc");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("refresh-token");

                    b.HasKey("UserId")
                        .HasName("p-k_microsoft-credentials");

                    b.ToTable("microsoft-credentials");
                });

            modelBuilder.Entity("VacApp_Bovinova_Platform.IAM.Domain.Model.Aggregates.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("created-at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("email-confirmed");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("updated-at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("p-k_users");

                    b.ToTable("users");
                });

            modelBuilder.Entity("VacApp_Bovinova_Platform.RanchManagement.Domain.Model.Aggregates.Bovine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime?>("BirthDate")
                        .IsRequired()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("birth-date");

                    b.Property<string>("BovineImg")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("bovine-img");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("breed");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("gender");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("RanchUserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<int?>("StableId")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("stable-id");

                    b.HasKey("Id")
                        .HasName("p-k_bovines");

                    b.HasIndex("StableId")
                        .HasDatabaseName("i-x_bovines_stable-id");

                    b.ToTable("bovines");
                });

            modelBuilder.Entity("VacApp_Bovinova_Platform.RanchManagement.Domain.Model.Aggregates.Stable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("Limit")
                        .HasColumnType("int")
                        .HasColumnName("limit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<int>("RanchUserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p-k_stables");

                    b.ToTable("stables");
                });

            modelBuilder.Entity("VacApp_Bovinova_Platform.RanchManagement.Domain.Model.Aggregates.Vaccine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("BovineId")
                        .HasColumnType("int")
                        .HasColumnName("bovine-id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("RanchUserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<DateTime?>("VaccineDate")
                        .IsRequired()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("vaccine-date");

                    b.Property<string>("VaccineImg")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("vaccine-img");

                    b.Property<string>("VaccineType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("vaccine-type");

                    b.HasKey("Id")
                        .HasName("p-k_vaccines");

                    b.HasIndex("BovineId")
                        .HasDatabaseName("i-x_vaccines_bovine-id");

                    b.ToTable("vaccines");
                });

            modelBuilder.Entity("VacApp_Bovinova_Platform.StaffAdministration.Domain.Model.Aggregates.Staff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int?>("CampaignId")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("campaign-id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("StaffUserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p-k_staff");

                    b.HasIndex("CampaignId")
                        .HasDatabaseName("i-x_staff_campaign-id");

                    b.ToTable("staff");
                });

            modelBuilder.Entity("VacApp_Bovinova_Platform.CampaignManagement.Domain.Model.Aggregates.Campaign", b =>
                {
                    b.HasOne("VacApp_Bovinova_Platform.RanchManagement.Domain.Model.Aggregates.Stable", "Stable")
                        .WithMany()
                        .HasForeignKey("StableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f-k_campaigns_-stable_stable-id");

                    b.Navigation("Stable");
                });

            modelBuilder.Entity("VacApp_Bovinova_Platform.CampaignManagement.Domain.Model.Aggregates.Channel", b =>
                {
                    b.HasOne("VacApp_Bovinova_Platform.CampaignManagement.Domain.Model.Aggregates.Campaign", null)
                        .WithMany("Channels")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f-k_channels_campaigns_campaign-id");
                });

            modelBuilder.Entity("VacApp_Bovinova_Platform.CampaignManagement.Domain.Model.Aggregates.Goal", b =>
                {
                    b.HasOne("VacApp_Bovinova_Platform.CampaignManagement.Domain.Model.Aggregates.Campaign", null)
                        .WithMany("Goals")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f-k_goals_campaigns_campaign-id");
                });

            modelBuilder.Entity("VacApp_Bovinova_Platform.RanchManagement.Domain.Model.Aggregates.Bovine", b =>
                {
                    b.HasOne("VacApp_Bovinova_Platform.RanchManagement.Domain.Model.Aggregates.Stable", "Stable")
                        .WithMany()
                        .HasForeignKey("StableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f-k_bovines_-stable_stable-id");

                    b.Navigation("Stable");
                });

            modelBuilder.Entity("VacApp_Bovinova_Platform.RanchManagement.Domain.Model.Aggregates.Vaccine", b =>
                {
                    b.HasOne("VacApp_Bovinova_Platform.RanchManagement.Domain.Model.Aggregates.Bovine", "Bovine")
                        .WithMany()
                        .HasForeignKey("BovineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f-k_vaccines_bovines_bovine-id");

                    b.Navigation("Bovine");
                });

            modelBuilder.Entity("VacApp_Bovinova_Platform.StaffAdministration.Domain.Model.Aggregates.Staff", b =>
                {
                    b.HasOne("VacApp_Bovinova_Platform.CampaignManagement.Domain.Model.Aggregates.Campaign", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f-k_staff_campaigns_campaign-id");

                    b.OwnsOne("VacApp_Bovinova_Platform.StaffAdministration.Domain.Model.ValueObjects.EmployeeStatus", "EmployeeStatus", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<int>("Value")
                                .HasColumnType("int")
                                .HasColumnName("employee_status");

                            b1.HasKey("Id")
                                .HasName("p-k_staff");

                            b1.ToTable("staff");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f-k_staff_staff_id");
                        });

                    b.Navigation("Campaign");

                    b.Navigation("EmployeeStatus")
                        .IsRequired();
                });

            modelBuilder.Entity("VacApp_Bovinova_Platform.CampaignManagement.Domain.Model.Aggregates.Campaign", b =>
                {
                    b.Navigation("Channels");

                    b.Navigation("Goals");
                });
#pragma warning restore 612, 618
        }
    }
}
